from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password
from rest_framework import serializers
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer

from rbac.models import Role

User = get_user_model()


def _validate_role_names(names):
    """Resolve a list of role names to Role objects, 400 on any unknown name."""
    names = list(dict.fromkeys(names or []))  # de-dupe, keep order
    roles = list(Role.objects.filter(name__in=names))
    found = {r.name for r in roles}
    missing = [n for n in names if n not in found]
    if missing:
        raise serializers.ValidationError(
            f"Unknown role(s): {', '.join(missing)}"
        )
    return roles


class UserSerializer(serializers.ModelSerializer):
    roles = serializers.SlugRelatedField(
        slug_field="name", many=True, read_only=True
    )
    permissions = serializers.SerializerMethodField()

    class Meta:
        model = User
        fields = [
            "id",
            "email",
            "full_name",
            "is_active",
            "is_staff",
            "mfa_enabled",
            "date_joined",
            "roles",
            "permissions",
        ]
        read_only_fields = fields

    def get_permissions(self, obj) -> list[str]:
        return sorted(obj.get_permission_codes())


class RegisterSerializer(serializers.ModelSerializer):
    password = serializers.CharField(
        write_only=True, style={"input_type": "password"},
        validators=[validate_password],
    )

    class Meta:
        model = User
        fields = ["id", "email", "full_name", "password"]
        read_only_fields = ["id"]

    def create(self, validated_data):
        user = User.objects.create_user(**validated_data)
        # New self-serve users get the least-privilege Viewer role if seeded.
        try:
            user.roles.add(Role.objects.get(name="Viewer"))
        except Role.DoesNotExist:
            pass
        return user


class AdminUserSerializer(serializers.ModelSerializer):
    """Full user view for the admin console (``user:admin``)."""

    roles = serializers.SlugRelatedField(
        slug_field="name", many=True, read_only=True
    )

    class Meta:
        model = User
        fields = [
            "id",
            "email",
            "full_name",
            "is_active",
            "is_staff",
            "is_superuser",
            "mfa_enabled",
            "date_joined",
            "last_login",
            "roles",
        ]
        read_only_fields = fields


class AdminUserCreateSerializer(serializers.ModelSerializer):
    """Admin-side user creation: email + name + an initial password + roles.

    Onboarding is admin-set-password only (no invite email): the raw password is
    chosen/generated by the admin and shown once in the UI, never stored.
    """

    password = serializers.CharField(
        write_only=True,
        style={"input_type": "password"},
        validators=[validate_password],
    )
    roles = serializers.ListField(
        child=serializers.CharField(), required=False, default=list
    )

    class Meta:
        model = User
        fields = ["id", "email", "full_name", "password", "roles"]
        read_only_fields = ["id"]

    def validate_roles(self, value):
        return _validate_role_names(value)

    def create(self, validated_data):
        roles = validated_data.pop("roles", [])
        user = User.objects.create_user(**validated_data)
        if roles:
            user.roles.set(roles)
        return user


class AdminUserUpdateSerializer(serializers.ModelSerializer):
    """Partial admin update: display name, active flag, and/or role set."""

    roles = serializers.ListField(
        child=serializers.CharField(), required=False
    )

    class Meta:
        model = User
        fields = ["full_name", "is_active", "roles"]

    def validate_roles(self, value):
        return _validate_role_names(value)

    def update(self, instance, validated_data):
        roles = validated_data.pop("roles", None)
        for attr, val in validated_data.items():
            setattr(instance, attr, val)
        instance.save()
        if roles is not None:
            instance.roles.set(roles)
        return instance


class SetPasswordSerializer(serializers.Serializer):
    """Admin sets another user's password (no current-password check)."""

    new_password = serializers.CharField(
        write_only=True,
        style={"input_type": "password"},
        validators=[validate_password],
    )


class PasswordChangeSerializer(serializers.Serializer):
    """Self-service change: verify the current password, then set the new one."""

    current_password = serializers.CharField(
        write_only=True, style={"input_type": "password"}
    )
    new_password = serializers.CharField(
        write_only=True,
        style={"input_type": "password"},
        validators=[validate_password],
    )

    def validate_current_password(self, value):
        user = self.context["request"].user
        if not user.check_password(value):
            raise serializers.ValidationError("Current password is incorrect.")
        return value


class ProfileUpdateSerializer(serializers.ModelSerializer):
    """Self-service profile edit (display name only)."""

    class Meta:
        model = User
        fields = ["full_name"]


class RoleSerializer(serializers.ModelSerializer):
    """Read-only role + its permission codes, for the roles reference page."""

    permissions = serializers.SlugRelatedField(
        slug_field="code", many=True, read_only=True
    )

    class Meta:
        model = Role
        fields = ["name", "description", "is_system", "permissions"]
        read_only_fields = fields


class SessionSerializer(serializers.Serializer):
    """One active refresh token (device/session) for the signed-in user."""

    jti = serializers.CharField()
    created_at = serializers.DateTimeField()
    expires_at = serializers.DateTimeField()


class OpusTokenObtainPairSerializer(TokenObtainPairSerializer):
    """Embeds identity + RBAC claims so client apps can authorize locally."""

    @classmethod
    def get_token(cls, user):
        token = super().get_token(user)
        token["email"] = user.email
        token["name"] = user.full_name
        token["roles"] = list(user.roles.values_list("name", flat=True))
        token["perms"] = sorted(user.get_permission_codes())
        return token
